Test code
139bercy/decp-rama-v2 pull request #67
Opened 2023-01-05 15:22 UTC by kaa-serpent

2023-01-05 15:47 UTC, HGInfoNancy requested changes

2023-01-05 15:47 UTC, HGInfoNancy commented on test_urls.py
> +
Faire un commentaire + remplacer try/except par un if keys

2023-01-24 09:17 UTC, kaa-serpent commented on test_urls.py
> +
if key vérifie la présence d'un contenue pour la cle mais pas la présence de la cle et ne rentre pas dans la condition else

2023-04-25 15:53 UTC, desrousseaux approved these changes

2023-04-26 14:06 UTC, merged